-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 15, 2022 at 11:01 AM
-- Server version: 5.7.36
-- PHP Version: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cooks_collection`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

DROP TABLE IF EXISTS `recipes`;
CREATE TABLE IF NOT EXISTS `recipes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(80) NOT NULL,
  `name` varchar(80) NOT NULL,
  `description` longtext NOT NULL,
  `time` int(11) NOT NULL,
  `diff` int(11) NOT NULL,
  `ingredients` longtext,
  `instructions` longtext,
  `image` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=112 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `category`, `name`, `description`, `time`, `diff`, `ingredients`, `instructions`, `image`) VALUES
(69, 'Lunch', 'Baba Ghanoush', 'Baba ghanoush, also spelled baba ganoush or baba ghanouj, is a Levantine appetizer consisting of finely chopped roasted eggplant, olive oil, lemon juice, various seasonings, and tahini. The Middle Eastern version consists of onions, tomatoes, or other vegetables', 30, 2, 'a:5:{i:1;a:3:{s:4:\"name\";s:8:\"eggplant\";s:6:\"amount\";s:3:\"500\";s:4:\"unit\";s:1:\"g\";}i:2;a:3:{s:4:\"name\";s:6:\"garlic\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:1:\"g\";}i:3;a:3:{s:4:\"name\";s:5:\"olive\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:4:\"cups\";}i:4;a:3:{s:4:\"name\";s:5:\"lemon\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:2:\"ml\";}i:5;a:3:{s:4:\"name\";s:6:\"tahini\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:2:\"ml\";}}', 'a:4:{i:1;a:1:{s:4:\"step\";s:48:\"Grill whole eggplant until skin blackens/charred\";}i:2;a:1:{s:4:\"step\";s:82:\"Place on tray, put into oven on 180C until soft all the way through, (20-30 mins) \";}i:3;a:1:{s:4:\"step\";s:66:\"while waiting to cool, combine the tahnini, garlic and lemon juice\";}i:4;a:1:{s:4:\"step\";s:59:\"mash eggplant with fork into paste & slowly add tahini mix \";}}', '6274cb923ec52.png'),
(70, 'Dessert', 'Berry Coulis', 'N/A', 5, 1, 'a:4:{i:1;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:2;a:3:{s:4:\"name\";s:11:\"brown sugar\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:3;a:3:{s:4:\"name\";s:11:\"lemon juice\";s:6:\"amount\";s:2:\"20\";s:4:\"unit\";s:2:\"ml\";}i:4;a:3:{s:4:\"name\";s:13:\"mixed berries\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:4:\"cups\";}}', 'a:4:{i:1;a:1:{s:4:\"step\";s:23:\"melt butter in saucepan\";}i:2;a:1:{s:4:\"step\";s:53:\"add brown sugar and lemon juice, stir until dissolved\";}i:3;a:1:{s:4:\"step\";s:60:\"add berries and toss gently to avoid breaking up the berries\";}i:4;a:1:{s:4:\"step\";s:68:\"cook until berries are warm and juices begin to release, 2-3 minutes\";}}', '6274cdb2d8087.jpg'),
(71, 'Dessert', 'Brownie in a Mug ', 'IN A MUG!!?? half recipe is plenty ', 5, 2, 'a:6:{i:1;a:3:{s:4:\"name\";s:5:\"flour\";s:6:\"amount\";s:2:\"34\";s:4:\"unit\";s:1:\"g\";}i:2;a:3:{s:4:\"name\";s:5:\"sugar\";s:6:\"amount\";s:2:\"57\";s:4:\"unit\";s:1:\"g\";}i:3;a:3:{s:4:\"name\";s:5:\"cocoa\";s:6:\"amount\";s:2:\"16\";s:4:\"unit\";s:1:\"g\";}i:4;a:3:{s:4:\"name\";s:4:\"milk\";s:6:\"amount\";s:2:\"30\";s:4:\"unit\";s:2:\"ml\";}i:5;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:2:\"30\";s:4:\"unit\";s:1:\"g\";}i:6;a:3:{s:4:\"name\";s:4:\"choc\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}}', 'a:3:{i:1;a:1:{s:4:\"step\";s:20:\"add dry ingredients \";}i:2;a:1:{s:4:\"step\";s:19:\"add wet ingredients\";}i:3;a:1:{s:4:\"step\";s:44:\"microwave 1m30s full recipe, 1m half recipe \";}}', '6274ce8f51792.jpg'),
(72, 'Dessert', 'Carrot Cake ', 'halve for cupcake ', 60, 6, 'a:15:{i:1;a:3:{s:4:\"name\";s:5:\"plain\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:4:\"cups\";}i:2;a:3:{s:4:\"name\";s:6:\"baking\";s:6:\"amount\";s:1:\"6\";s:4:\"unit\";s:1:\"g\";}i:3;a:3:{s:4:\"name\";s:6:\"bicarb\";s:6:\"amount\";s:1:\"6\";s:4:\"unit\";s:1:\"g\";}i:4;a:3:{s:4:\"name\";s:4:\"salt\";s:6:\"amount\";s:1:\"5\";s:4:\"unit\";s:1:\"g\";}i:5;a:3:{s:4:\"name\";s:6:\"ground\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:1:\"g\";}i:6;a:3:{s:4:\"name\";s:6:\"ground\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:1:\"g\";}i:7;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:3:\"340\";s:4:\"unit\";s:1:\"g\";}i:8;a:3:{s:4:\"name\";s:5:\"brown\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:9;a:3:{s:4:\"name\";s:3:\"egg\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:1:\"g\";}i:10;a:3:{s:4:\"name\";s:7:\"vanilla\";s:6:\"amount\";s:2:\"12\";s:4:\"unit\";s:1:\"g\";}i:11;a:3:{s:4:\"name\";s:5:\"water\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:12;a:3:{s:4:\"name\";s:6:\"grated\";s:6:\"amount\";s:3:\"450\";s:4:\"unit\";s:1:\"g\";}i:13;a:3:{s:4:\"name\";s:5:\"pecan\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:4:\"cups\";}i:14;a:3:{s:4:\"name\";s:8:\"cinnamon\";s:6:\"amount\";s:1:\"5\";s:4:\"unit\";s:1:\"g\";}i:15;a:3:{s:4:\"name\";s:5:\"sugar\";s:6:\"amount\";s:3:\"113\";s:4:\"unit\";s:1:\"g\";}}', 'a:6:{i:1;a:1:{s:4:\"step\";s:52:\"preheat over to 175C grease 3 9 inch round cake pans\";}i:2;a:1:{s:4:\"step\";s:76:\"whisk together flour, baking powder, soda, cinnamon, salt, ginger and nutmeg\";}i:3;a:1:{s:4:\"step\";s:110:\"beat butter and sugar w/ mixer. add eggs one at a time. add vanilla, water and carrots and beat until combined\";}i:4;a:1:{s:4:\"step\";s:54:\"add the flour mix to the wet and mix. then add pecans \";}i:5;a:1:{s:4:\"step\";s:114:\"divide batter evenly into pans. bake- rotating half way through until golden ~30mins let cool in pan for 15 mins  \";}i:6;a:1:{s:4:\"step\";s:173:\"using serrated knife, trim rounded top off two cakes. place one trimmed cake (right side up) on platter. Top w/ ne cup of frosting, place trimmed cake cut side down on top. \";}}', '6274d5a6cacf2.png'),
(73, 'Dinner', 'Chicken Parma Tomato Sauce ', 'just the sauce', 70, 3, 'a:10:{i:1;a:3:{s:4:\"name\";s:5:\"onion\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:2;a:3:{s:4:\"name\";s:6:\"carrot\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"cups\";}i:3;a:3:{s:4:\"name\";s:7:\"garllic\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:4:\"cups\";}i:4;a:3:{s:4:\"name\";s:7:\"passata\";s:6:\"amount\";s:3:\"300\";s:4:\"unit\";s:2:\"ml\";}i:5;a:3:{s:4:\"name\";s:5:\"white\";s:6:\"amount\";s:3:\"100\";s:4:\"unit\";s:2:\"ml\";}i:6;a:3:{s:4:\"name\";s:7:\"chicken\";s:6:\"amount\";s:3:\"200\";s:4:\"unit\";s:2:\"ml\";}i:7;a:3:{s:4:\"name\";s:8:\"balsamic\";s:6:\"amount\";s:2:\"10\";s:4:\"unit\";s:2:\"ml\";}i:8;a:3:{s:4:\"name\";s:5:\"basil\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:1:\"g\";}i:9;a:3:{s:4:\"name\";s:4:\"salt\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:1:\"g\";}i:10;a:3:{s:4:\"name\";s:6:\"tomato\";s:6:\"amount\";s:2:\"15\";s:4:\"unit\";s:1:\"g\";}}', 'a:4:{i:1;a:1:{s:4:\"step\";s:77:\"chop onion carrot and garlic finely & fry in olive oil 2-3 minutes until soft\";}i:2;a:1:{s:4:\"step\";s:64:\"add wine, passata, stock, vinegar, and paste and bring to a boil\";}i:3;a:1:{s:4:\"step\";s:34:\"turn to low and let simmer for ~1h\";}i:4;a:1:{s:4:\"step\";s:31:\"when cooled, blend until smooth\";}}', '6274d9facafdf.jpg'),
(74, 'Dessert', 'Chocolate Pecan Chess Pie', 'Checkers', 150, 7, 'a:16:{i:1;a:3:{s:4:\"name\";s:6:\"pastry\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:2;a:3:{s:4:\"name\";s:5:\"flour\";s:6:\"amount\";s:4:\"1.25\";s:4:\"unit\";s:6:\"cup(s)\";}i:3;a:3:{s:4:\"name\";s:5:\"sugar\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"tsp.\";}i:4;a:3:{s:4:\"name\";s:4:\"salt\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:4:\"tsp.\";}i:5;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:3:\"110\";s:4:\"unit\";s:1:\"g\";}i:6;a:3:{s:4:\"name\";s:3:\"ice\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:7;a:3:{s:4:\"name\";s:5:\"flour\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:5:\"tbsp.\";}i:8;a:3:{s:4:\"name\";s:10:\"evaporated\";s:6:\"amount\";s:4:\"0.66\";s:4:\"unit\";s:6:\"cup(s)\";}i:9;a:3:{s:4:\"name\";s:4:\"eggs\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:3:\"ea.\";}i:10;a:3:{s:4:\"name\";s:5:\"sugar\";s:6:\"amount\";s:3:\"1.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:11;a:3:{s:4:\"name\";s:5:\"cocoa\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:5:\"tbsp.\";}i:12;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:3:\"115\";s:4:\"unit\";s:1:\"g\";}i:13;a:3:{s:4:\"name\";s:4:\"dark\";s:6:\"amount\";s:2:\"60\";s:4:\"unit\";s:1:\"g\";}i:14;a:3:{s:4:\"name\";s:6:\"pecans\";s:6:\"amount\";s:3:\"1.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:15;a:3:{s:4:\"name\";s:5:\"brown\";s:6:\"amount\";s:4:\"0.66\";s:4:\"unit\";s:6:\"cup(s)\";}i:16;a:3:{s:4:\"name\";s:6:\"golden\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:5:\"tbsp.\";}}', 'a:8:{i:1;a:1:{s:4:\"step\";s:20:\"Preheat oven to 170C\";}i:2;a:1:{s:4:\"step\";s:117:\"combine all pastry ingredients in food processer. add ice water until it forms a ball. wrap and refrigerate min 1hr. \";}i:3;a:1:{s:4:\"step\";s:43:\"roll out pastry and line 23 cm pan/cake tin\";}i:4;a:1:{s:4:\"step\";s:93:\"melt butter and chocolate (30 secs in microwave) whisk into evaporated milk, eggs, 1tsp vanil\";}i:5;a:1:{s:4:\"step\";s:69:\"stir sugar, cocoa, flour in separate bowl then whisk into wet mixute \";}i:6;a:1:{s:4:\"step\";s:20:\"bake for 45 minutes \";}i:7;a:1:{s:4:\"step\";s:76:\"stir pecans, sugar, syrups. put on top of pie when it comes out of the oven.\";}i:8;a:1:{s:4:\"step\";s:81:\"put back in oven for 15 minutes, buts should be brown, let cool, serve with cream\";}}', '627de61cbb6fc.jpg'),
(75, 'Dinner', 'Chorizo, Potato &amp; Spinach Soup', 'good soup', 45, 3, 'a:9:{i:1;a:3:{s:4:\"name\";s:3:\"Big\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:3:\"ea.\";}i:2;a:3:{s:4:\"name\";s:6:\"garlic\";s:6:\"amount\";s:1:\"4\";s:4:\"unit\";s:3:\"ea.\";}i:3;a:3:{s:4:\"name\";s:5:\"olive\";s:6:\"amount\";s:1:\"4\";s:4:\"unit\";s:5:\"tbsp.\";}i:4;a:3:{s:4:\"name\";s:3:\"big\";s:6:\"amount\";s:1:\"6\";s:4:\"unit\";s:3:\"ea.\";}i:5;a:3:{s:4:\"name\";s:9:\"vegetable\";s:6:\"amount\";s:3:\"1.5\";s:4:\"unit\";s:1:\"L\";}i:6;a:3:{s:4:\"name\";s:7:\"chorizo\";s:6:\"amount\";s:3:\"300\";s:4:\"unit\";s:1:\"g\";}i:7;a:3:{s:4:\"name\";s:7:\"spinach\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:8;a:3:{s:4:\"name\";s:3:\"bay\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:3:\"ea.\";}i:9;a:3:{s:4:\"name\";s:5:\"bread\";s:6:\"amount\";s:1:\"5\";s:4:\"unit\";s:3:\"ea.\";}}', 'a:9:{i:1;a:1:{s:4:\"step\";s:66:\"in a big pan, sweat onion and garlic for 5 mins until transparent \";}i:2;a:1:{s:4:\"step\";s:27:\"add potato to absorb flavor\";}i:3;a:1:{s:4:\"step\";s:34:\"add in sausage and continue sweat \";}i:4;a:1:{s:4:\"step\";s:24:\"add stock and bay leaves\";}i:5;a:1:{s:4:\"step\";s:38:\"cook until potatoes are soft - 15 mins\";}i:6;a:1:{s:4:\"step\";s:50:\"chop spinach real fine and blanch for 1 min, drain\";}i:7;a:1:{s:4:\"step\";s:35:\"mash potatoes to make thick chowder\";}i:8;a:1:{s:4:\"step\";s:39:\"add spinach, simmer for couple of mins \";}i:9;a:1:{s:4:\"step\";s:25:\"mix paprika and olive oil\";}}', '627de892d8bd8.jpg'),
(76, 'Dinner', 'Country Chicken Pie', 'CHICKEN PIE', 45, 6, 'a:14:{i:1;a:3:{s:4:\"name\";s:5:\"olive\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:5:\"tbsp.\";}i:2;a:3:{s:4:\"name\";s:7:\"chicken\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:3;a:3:{s:4:\"name\";s:9:\"mushrooms\";s:6:\"amount\";s:3:\"200\";s:4:\"unit\";s:1:\"g\";}i:4;a:3:{s:4:\"name\";s:5:\"plain\";s:6:\"amount\";s:4:\"0.25\";s:4:\"unit\";s:6:\"cup(s)\";}i:5;a:3:{s:4:\"name\";s:9:\"thickened\";s:6:\"amount\";s:3:\"300\";s:4:\"unit\";s:2:\"mL\";}i:6;a:3:{s:4:\"name\";s:5:\"white\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:7;a:3:{s:4:\"name\";s:7:\"chicken\";s:6:\"amount\";s:3:\"1.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:8;a:3:{s:4:\"name\";s:5:\"herbs\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:9;a:3:{s:4:\"name\";s:6:\"ground\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"tsp.\";}i:10;a:3:{s:4:\"name\";s:7:\"English\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:11;a:3:{s:4:\"name\";s:8:\"potatoes\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:3:\"ea.\";}i:12;a:3:{s:4:\"name\";s:6:\"grated\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:6:\"cup(s)\";}i:13;a:3:{s:4:\"name\";s:3:\"egg\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:14;a:3:{s:4:\"name\";s:5:\"bacon\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:3:\"ea.\";}}', 'a:9:{i:1;a:1:{s:4:\"step\";s:20:\"preheat oven to 180C\";}i:2;a:1:{s:4:\"step\";s:54:\"heat oil and add chicken bacon and mushrooms for 5mins\";}i:3;a:1:{s:4:\"step\";s:50:\"reduce heat and add flour, stir until paste forms \";}i:4;a:1:{s:4:\"step\";s:75:\"increase heat and add wine, reduce then add cream, chicken stock and herbs \";}i:5;a:1:{s:4:\"step\";s:58:\"place spinach in bowl, and microwave until wilted (3 mins)\";}i:6;a:1:{s:4:\"step\";s:81:\"place potatoes in bottom of pie bowl, top w/ chicken mixture, spinach and cheese \";}i:7;a:1:{s:4:\"step\";s:50:\"place pastry on top of pie and seal with egg wash \";}i:8;a:1:{s:4:\"step\";s:51:\"brush egg wash on top and puncture a hole in pastry\";}i:9;a:1:{s:4:\"step\";s:38:\"bake for 25 mins/until pastry is solid\";}}', '627dee419dd45.jpeg'),
(77, 'Lunch', 'Dumplings', 'stop staring at my dumpy-lings\r\ngyoza right in my mouth ', 200, 9, 'a:11:{i:1;a:3:{s:4:\"name\";s:11:\"minced beef\";s:6:\"amount\";s:3:\"500\";s:4:\"unit\";s:1:\"g\";}i:2;a:3:{s:4:\"name\";s:7:\"spinach\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:2:\"kg\";}i:3;a:3:{s:4:\"name\";s:13:\"shoaxing wine\";s:6:\"amount\";s:4:\"0.66\";s:4:\"unit\";s:6:\"cup(s)\";}i:4;a:3:{s:4:\"name\";s:10:\"canola oil\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:5;a:3:{s:4:\"name\";s:10:\"sesame oil\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:5:\"tbsp.\";}i:6;a:3:{s:4:\"name\";s:4:\"salt\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:5:\"tbsp.\";}i:7;a:3:{s:4:\"name\";s:9:\"soy sauce\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:4:\"tsp.\";}i:8;a:3:{s:4:\"name\";s:12:\"white pepper\";s:6:\"amount\";s:4:\"0.25\";s:4:\"unit\";s:4:\"tsp.\";}i:9;a:3:{s:4:\"name\";s:5:\"water\";s:6:\"amount\";s:4:\"0.66\";s:4:\"unit\";s:6:\"cup(s)\";}i:10;a:3:{s:4:\"name\";s:21:\"dumpling wrapper pack\";s:6:\"amount\";s:1:\"6\";s:4:\"unit\";s:3:\"ea.\";}i:11;a:3:{s:4:\"name\";s:4:\"love\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:9:\"pinch(es)\";}}', 'a:3:{i:1;a:1:{s:4:\"step\";s:51:\"mix all ingredients in bowl until well combined \r\n \";}i:2;a:1:{s:4:\"step\";s:246:\"to wrap: dampen edges of circle with water, put < tbl of filling in middle. fold in half and pinch at top. make 2 folds on each side until dumpling looks like a fan. make sure its completely sealed. put dumpling on a baking tray lined with paper \";}i:3;a:1:{s:4:\"step\";s:21:\"boil until they float\";}}', '627e072b4f029.jpg'),
(81, 'Lunch', 'Hommus', 'Whats the difference between Black Eyed Peas and Chickpeas?\r\nBlack Eyed Peas can sing us a song and Chickpeas can only Hummus one.', 5, 2, 'a:6:{i:1;a:3:{s:4:\"name\";s:6:\"canned\";s:6:\"amount\";s:3:\"400\";s:4:\"unit\";s:1:\"g\";}i:2;a:3:{s:4:\"name\";s:6:\"garlic\";s:6:\"amount\";s:1:\"2\";s:4:\"unit\";s:3:\"ea.\";}i:3;a:3:{s:4:\"name\";s:5:\"olive\";s:6:\"amount\";s:2:\"66\";s:4:\"unit\";s:2:\"mL\";}i:4;a:3:{s:4:\"name\";s:6:\"tahini\";s:6:\"amount\";s:3:\"1.2\";s:4:\"unit\";s:5:\"tbsp.\";}i:5;a:3:{s:4:\"name\";s:6:\"ground\";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:4:\"tsp.\";}i:6;a:3:{s:4:\"name\";s:5:\"water\";s:6:\"amount\";s:2:\"40\";s:4:\"unit\";s:2:\"mL\";}}', 'a:3:{i:1;a:1:{s:4:\"step\";s:69:\"place chickpeas, garlic, tahini, cumin and lemon juice into a blender\";}i:2;a:1:{s:4:\"step\";s:20:\"slowly add olive oil\";}i:3;a:1:{s:4:\"step\";s:36:\"slowly add water, blend until smooth\";}}', '627e0cf899ba2.jpg'),
(80, 'Breakfast', 'Hollandaise Sauce', 'fly me away away youre my holiday', 5, 2, 'a:3:{i:1;a:3:{s:4:\"name\";s:12:\"lemon juice \";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:5:\"tbsp.\";}i:2;a:3:{s:4:\"name\";s:9:\"egg yolk \";s:6:\"amount\";s:1:\"1\";s:4:\"unit\";s:3:\"ea.\";}i:3;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:2:\"37\";s:4:\"unit\";s:1:\"g\";}}', 'a:4:{i:1;a:1:{s:4:\"step\";s:24:\"melt butter in microwave\";}i:2;a:1:{s:4:\"step\";s:48:\"mix egg yolk and lemon together in separate bowl\";}i:3;a:1:{s:4:\"step\";s:32:\"whisk egg mix into melted butter\";}i:4;a:1:{s:4:\"step\";s:80:\"blast in microwave for 15 seconds at a time until desired consistency is reached\";}}', '627e0ac93098f.jpg'),
(82, 'Dessert', 'Lemon Cheese Cake', 'is it a cheese\r\nor is it a cake', 120, 5, 'a:7:{i:1;a:3:{s:4:\"name\";s:5:\"plain\";s:6:\"amount\";s:3:\"250\";s:4:\"unit\";s:1:\"g\";}i:2;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:3:\"125\";s:4:\"unit\";s:1:\"g\";}i:3;a:3:{s:4:\"name\";s:3:\"egg\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:3:\"ea.\";}i:4;a:3:{s:4:\"name\";s:6:\"caster\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:6:\"cup(s)\";}i:5;a:3:{s:4:\"name\";s:5:\"cream\";s:6:\"amount\";s:3:\"750\";s:4:\"unit\";s:1:\"g\";}i:6;a:3:{s:4:\"name\";s:5:\"lemon\";s:6:\"amount\";s:1:\"3\";s:4:\"unit\";s:4:\"tsp.\";}i:7;a:3:{s:4:\"name\";s:5:\"lemon\";s:6:\"amount\";s:4:\"0.25\";s:4:\"unit\";s:6:\"cup(s)\";}}', 'a:9:{i:1;a:1:{s:4:\"step\";s:30:\"lightly grease spring form tin\";}i:2;a:1:{s:4:\"step\";s:43:\"combine biscuit crumbs and butter in a bowl\";}i:3;a:1:{s:4:\"step\";s:46:\"press crumbs evenly over base and side of tin \";}i:4;a:1:{s:4:\"step\";s:23:\"refrigerate for an hour\";}i:5;a:1:{s:4:\"step\";s:69:\"beat eggs and sugar in bowl with electric mixer until pale and thick \";}i:6;a:1:{s:4:\"step\";s:32:\"add cheese rind and lemon juice \";}i:7;a:1:{s:4:\"step\";s:29:\"beat until smooth and creamy \";}i:8;a:1:{s:4:\"step\";s:59:\"pour mixture into tin and bake in moderate oven for 45 mins\";}i:9;a:1:{s:4:\"step\";s:23:\"cool, then refrigerate \";}}', '627e165977bd9.jpeg'),
(83, 'Dinner', 'Mac &amp; Cheese', 'if is easy mac is too easy', 40, 4, 'a:9:{i:1;a:3:{s:4:\"name\";s:5:\"bacon\";s:6:\"amount\";s:1:\"6\";s:4:\"unit\";s:3:\"ea.\";}i:2;a:3:{s:4:\"name\";s:5:\"panko\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:2:\"mg\";}i:3;a:3:{s:4:\"name\";s:5:\"elbow\";s:6:\"amount\";s:3:\"500\";s:4:\"unit\";s:1:\"g\";}i:4;a:3:{s:4:\"name\";s:6:\"butter\";s:6:\"amount\";s:2:\"70\";s:4:\"unit\";s:1:\"g\";}i:5;a:3:{s:4:\"name\";s:5:\"fl0ur\";s:6:\"amount\";s:4:\"0.33\";s:4:\"unit\";s:6:\"cup(s)\";}i:6;a:3:{s:4:\"name\";s:4:\"milk\";s:6:\"amount\";s:1:\"4\";s:4:\"unit\";s:6:\"cup(s)\";}i:7;a:3:{s:4:\"name\";s:8:\"parmesan\";s:6:\"amount\";s:2:\"40\";s:4:\"unit\";s:1:\"g\";}i:8;a:3:{s:4:\"name\";s:9:\"Jarlsberg\";s:6:\"amount\";s:3:\"150\";s:4:\"unit\";s:1:\"g\";}i:9;a:3:{s:4:\"name\";s:7:\"cheddar\";s:6:\"amount\";s:3:\"150\";s:4:\"unit\";s:1:\"g\";}}', 'a:10:{i:1;a:1:{s:4:\"step\";s:20:\"preheat oven to 175C\";}i:2;a:1:{s:4:\"step\";s:57:\"cook bacon in non stick pan until golden, add breadcrumbs\";}i:3;a:1:{s:4:\"step\";s:91:\"melt butter in saucepan over med heat, whisk in flour and cook for 1 min, add s&p to taste \";}i:4;a:1:{s:4:\"step\";s:34:\"slowly whisk in milk until smooth \";}i:5;a:1:{s:4:\"step\";s:112:\"bring to simmer, reduce heat to low and simmer until sauce thickens (thick enough to coat pasta but still runny)\";}i:6;a:1:{s:4:\"step\";s:58:\"remove from heat and add all 3 cheeses, whisk until smooth\";}i:7;a:1:{s:4:\"step\";s:47:\"add cooked pasta to sauce and stir until coated\";}i:8;a:1:{s:4:\"step\";s:79:\"pour macaroni into a large baking dish, sprinkle bacon/breadcrumbs over the top\";}i:9;a:1:{s:4:\"step\";s:19:\"cook for 15-20 mins\";}i:10;a:1:{s:4:\"step\";s:6:\"enjoy \";}}', '627e18e930f65.jpg'),
(84, 'Dessert', 'Smoothie', 'smooth operatorrrrrr', 10, 1, 'a:5:{i:1;a:3:{s:4:\"name\";s:6:\"banana\";s:6:\"amount\";s:3:\"0.5\";s:4:\"unit\";s:3:\"ea.\";}i:2;a:3:{s:4:\"name\";s:5:\"mango\";s:6:\"amount\";s:2:\"80\";s:4:\"unit\";s:1:\"g\";}i:3;a:3:{s:4:\"name\";s:10:\"strawberry\";s:6:\"amount\";s:2:\"50\";s:4:\"unit\";s:1:\"g\";}i:4;a:3:{s:4:\"name\";s:8:\"spinnach\";s:6:\"amount\";s:2:\"70\";s:4:\"unit\";s:1:\"g\";}i:5;a:3:{s:4:\"name\";s:5:\"water\";s:6:\"amount\";s:4:\"0.75\";s:4:\"unit\";s:6:\"cup(s)\";}}', 'a:1:{i:1;a:1:{s:4:\"step\";s:5:\"blend\";}}', '627e19bb6720b.png');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
